elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"

sm_admin:
    resource: "@SMAdminBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
