# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        SM\Bundle\AdminBundle\Entity\Admin:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]



    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        administrators:
            entity: { class: SMAdminBundle:Admin, property: username }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        demo_login:
            pattern:  ^/admin/login$
            security: false

        # secures part of the application
        demo_secured_area:
            pattern:    ^/admin
            provider: administrators
            # it's important to notice that in this case _demo_security_check and _demo_login
            # are route names and that they are specified in the AcmeDemoBundle
            form_login:
                check_path: admin_security_check
                login_path: admin_login

                always_use_default_target_path: true
                default_target_path:            sm_admin_homepage
                use_referer:                    true
            logout:
                path:   admin_logout
                target: admin_login
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/efconnect, roles: ROLE_ADMIN }
        - { path: ^/elfinder, roles: ROLE_ADMIN }
